services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?POSTGRES_USER env var is missing on .env file}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD env var is missing on .env file}
      - POSTGRES_DB=${POSTGRES_DB:?POSTGRES_DB env var is missing on .env file}
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
